#!/bin/sh

APPDIR=$(dirname "$0")
java  -Djava.library.path="$APPDIR" -cp "$APPDIR/lib/StippleGen_2.jar:$APPDIR/lib/core.jar:$APPDIR/lib/controlP5.jar:$APPDIR/lib/toxiclibscore.jar:$APPDIR/lib/toxiclibs_p5.jar" StippleGen_2
