char * stringlst = [
N_("Matte jelly"), N_("ABCs"), N_("Bulging, matte jelly covering"),
N_("Smart jelly"), N_("Bevels"), N_("Same as Matte jelly but with more controls"),
N_("Metal casting"), N_("Bevels"), N_("Smooth drop-like bevel with metallic finish"),
N_("Motion blur, horizontal"), N_("Blurs"), N_("Blur as if the object flies horizontally; adjust Standard Deviation to vary force"),
N_("Motion blur, vertical"), N_("Blurs"), N_("Blur as if the object flies vertically; adjust Standard Deviation to vary force"),
N_("Apparition"), N_("Blurs"), N_("Edges are partly feathered out"),
N_("Cutout"), N_("Shadows and Glows"), N_("Drop shadow under the cut-out of the shape"),
N_("Jigsaw piece"), N_("Bevels"), N_("Low, sharp bevel"),
N_("Roughen"), N_("ABCs"), N_("Small-scale roughening to edges and content"),
N_("Rubber stamp"), N_("Overlays"), N_("Random whiteouts inside"),
N_("Ink bleed"), N_("Protrusions"), N_("Inky splotches underneath the object"),
N_("Fire"), N_("Protrusions"), N_("Edges of object are on fire"),
N_("Bloom"), N_("Bevels"), N_("Soft, cushion-like bevel with matte highlights"),
N_("Ridged border"), N_("Bevels"), N_("Ridged border with inner bevel"),
N_("Ripple"), N_("Distort"), N_("Horizontal rippling of edges"),
N_("Speckle"), N_("Overlays"), N_("Fill object with sparse translucent specks"),
N_("Oil slick"), N_("Overlays"), N_("Rainbow-colored semitransparent oily splotches"),
N_("Frost"), N_("Overlays"), N_("Flake-like white splotches"),
N_("Leopard fur"), N_("Materials"), N_("Leopard spots (loses object's own color)"),
N_("Zebra"), N_("Overlays"), N_("Irregular vertical dark stripes (loses object's own color)"),
N_("Clouds"), N_("Overlays"), N_("Airy, fluffy, sparse white clouds"),
N_("Sharpen"), N_("Image effects"), N_("Sharpen edges and boundaries within the object, force=0.15"),
N_("Sharpen more"), N_("Image effects"), N_("Sharpen edges and boundaries within the object, force=0.3"),
N_("Oil painting"), N_("Image effects"), N_("Simulate oil painting style"),
N_("Edge detect"), N_("Image effects"), N_("Detect color edges in object"),
N_("Horizontal edge detect"), N_("Image effects"), N_("Detect horizontal color edges in object"),
N_("Vertical edge detect"), N_("Image effects"), N_("Detect vertical color edges in object"),
N_("Pencil"), N_("Image effects"), N_("Detect color edges and retrace them in grayscale"),
N_("Blueprint"), N_("Image effects"), N_("Detect color edges and retrace them in blue"),
N_("Desaturate"), N_("Color"), N_("Render in shades of gray by reducing saturation to zero"),
N_("Invert"), N_("Color"), N_("Invert colors"),
N_("Sepia"), N_("Color"), N_("Render in warm sepia tones"),
N_("Age"), N_("Image effects"), N_("Imitate aged photograph"),
N_("Organic"), N_("Textures"), N_("Bulging, knotty, slick 3D surface"),
N_("Barbed wire"), N_("Overlays"), N_("Gray bevelled wires with drop shadows"),
N_("Swiss cheese"), N_("Overlays"), N_("Random inner-bevel holes"),
N_("Blue cheese"), N_("Overlays"), N_("Marble-like bluish speckles"),
N_("Button"), N_("Bevels"), N_("Soft bevel, slightly depressed middle"),
N_("Inset"), N_("Shadows and Glows"), N_("Shadowy outer bevel"),
N_("Dripping"), N_("Protrusions"), N_("Random paint streaks downwards"),
N_("Jam spread"), N_("Textures"), N_("Glossy clumpy jam spread"),
N_("Pixel smear"), N_("Distort"), N_("Van Gogh painting effect for bitmaps"),
N_("HSL Bumps"), N_("Bumps"), N_("Highly flexible bump combining diffuse and specular lightings"),
N_("Cracked glass"), N_("Textures"), N_("Under a cracked glass"),
N_("Bubbly Bumps"), N_("Bumps"), N_("Flexible bubbles effect with some displacement"),
N_("Glowing bubble"), N_("Ridges"), N_("Bubble effect with refraction and glow"),
N_("Neon"), N_("Bevels"), N_("Neon light effect"),
N_("Molten metal"), N_("Bevels"), N_("Melting parts of object together, with a glossy bevel and a glow"),
N_("Pressed steel"), N_("Bevels"), N_("Pressed metal with a rolled edge"),
N_("Matte bevel"), N_("Bevels"), N_("Soft, pastel-colored, blurry bevel"),
N_("Thin Membrane"), N_("Ridges"), N_("Thin like a soap membrane"),
N_("Matte ridge"), N_("Ridges"), N_("Soft pastel ridge"),
N_("Glowing metal"), N_("Bevels"), N_("Glowing metal texture"),
N_("Leaves"), N_("Scatter"), N_("Leaves on the ground in Fall, or living foliage"),
N_("Translucent"), N_("Bevels"), N_("Illuminated translucent plastic or glass effect"),
N_("Cross-smooth"), N_("Blurs"), N_("Blur inner borders and intersections"),
N_("Iridescent beeswax"), N_("Materials"), N_("Waxy texture which keeps its iridescence through color fill change"),
N_("Eroded metal"), N_("Materials"), N_("Eroded metal texture with ridges, grooves, holes and bumps"),
N_("Cracked Lava"), N_("Materials"), N_("A volcanic texture, a little like leather"),
N_("Bark"), N_("Textures"), N_("Bark texture, vertical; use with deep colors"),
N_("Lizard skin"), N_("Materials"), N_("Stylized reptile skin texture"),
N_("Stone wall"), N_("Textures"), N_("Stone wall texture to use with not too saturated colors"),
N_("Silk carpet"), N_("Textures"), N_("Silk carpet texture, horizontal stripes"),
N_("Refractive gel A"), N_("Ridges"), N_("Gel effect with light refraction"),
N_("Refractive gel B"), N_("Ridges"), N_("Gel effect with strong refraction"),
N_("Metallized paint"), N_("Materials"), N_("Metallized effect with a soft lighting, slightly translucent at the edges"),
N_("Dragee"), N_("Ridges"), N_("Gel Ridge with a pearlescent look"),
N_("Raised border"), N_("Bevels"), N_("Strongly raised border around a flat surface"),
N_("Metallized ridge"), N_("Ridges"), N_("Gel Ridge metallized at its top"),
N_("Fat oil"), N_("Bevels"), N_("Fat oil with some adjustable turbulence"),
N_("Colorize"), N_("Color"), N_("Blend image or object with a flood color and set lightness and contrast"),
N_("Parallel hollow"), N_("Morphology"), N_("A blurry hollow going parallel to the edge on the inside"),
N_("Hole"), N_("Morphology"), N_("Opens a smooth hole inside the shape"),
N_("Black hole"), N_("Morphology"), N_("Creates a black light inside and outside"),
N_("Smooth outline"), N_("Morphology"), N_("Outlining the lines and smoothing their crossings"),
N_("Cubes"), N_("Scatter"), N_("Scattered cubes; adjust the Morphology primitive to vary size"),
N_("Peel off"), N_("Materials"), N_("Peeling painting on a wall"),
N_("Gold splatter"), N_("Materials"), N_("Splattered cast metal, with golden highlights"),
N_("Gold paste"), N_("Materials"), N_("Fat pasted cast metal, with golden highlights"),
N_("Crumpled plastic"), N_("Textures"), N_("Crumpled matte plastic, with melted edge"),
N_("Enamel jewelry"), N_("Materials"), N_("Slightly cracked enameled texture"),
N_("Rough paper"), N_("Textures"), N_("Aquarelle paper effect which can be used for pictures as for objects"),
N_("Rough and glossy"), N_("Textures"), N_("Crumpled glossy paper effect which can be used for pictures as for objects"),
N_("In and Out"), N_("Shadows and Glows"), N_("Inner colorized shadow, outer black shadow"),
N_("Air spray"), N_("Scatter"), N_("Convert to small scattered particles with some thickness"),
N_("Warm inside"), N_("Morphology"), N_("Blurred colorized contour, filled inside"),
N_("Cool outside"), N_("Morphology"), N_("Blurred colorized contour, empty inside"),
N_("Electronic microscopy"), N_("Bevels"), N_("Bevel, crude light, discoloration and glow like in electronic microscopy"),
N_("Tartan"), N_("Overlays"), N_("Checkered tartan pattern"),
N_("Invert hue"), N_("Color"), N_("Invert hue, or rotate it"),
N_("Inner outline"), N_("Morphology"), N_("Draws an outline around"),
N_("Outline, double"), N_("Morphology"), N_("Draws a smooth line inside colorized with the color it overlays"),
N_("Fancy blur"), N_("Blurs"), N_("Smooth colorized contour which allows desaturation and hue rotation"),
N_("Glow"), N_("Shadows and Glows"), N_("Glow of object's own color at the edges"),
N_("Outline"), N_("Morphology"), N_("Adds a glowing blur and removes the shape"),
N_("Color emboss"), N_("Bumps"), N_("Classic or colorized emboss effect: grayscale, color and 3D relief"),
N_("Solarize"), N_("Color"), N_("Classical photographic solarization effect"),
N_("Moonarize"), N_("Color"), N_("An effect between solarize and invert which often preserves sky and water lights"),
N_("Soft focus lens"), N_("Image effects"), N_("Glowing image content without blurring it"),
N_("Stained glass"), N_("Bevels"), N_("Illuminated stained glass effect"),
N_("Dark glass"), N_("Bevels"), N_("Illuminated glass effect with light coming from beneath"),
N_("HSL Bumps alpha"), N_("Image effects, transparent"), N_("Same as HSL Bumps but with transparent highlights"),
N_("Bubbly Bumps alpha"), N_("Image effects, transparent"), N_("Same as Bubbly Bumps but with transparent highlights"),
N_("Smooth edges"), N_("Morphology"), N_("Smooth the outside of shapes and pictures without altering their contents"),
N_("Torn edges"), N_("Distort"), N_("Displace the outside of shapes and pictures without altering their content"),
N_("Feather"), N_("ABCs"), N_("Blurred mask on the edge without altering the contents"),
N_("Blur content"), N_("Blurs"), N_("Blur the contents of objects, preserving the outline"),
N_("Specular light"), N_("ABCs"), N_("Basic specular bevel to use for building textures"),
N_("Roughen inside"), N_("Distort"), N_("Roughen all inside shapes"),
N_("Evanescent"), N_("Blurs"), N_("Blur the contents of objects, preserving the outline and adding progressive transparency at edges"),
N_("Chalk and sponge"), N_("Distort"), N_("Low turbulence gives sponge look and high turbulence chalk"),
N_("People"), N_("Overlays"), N_("Colorized blotches, like a crowd of people"),
N_("Scotland"), N_("Overlays"), N_("Colorized mountain tops out of the fog"),
N_("Noise transparency"), N_("ABCs"), N_("Basic noise transparency texture"),
N_("Noise fill"), N_("ABCs"), N_("Basic noise fill texture; adjust color in Flood"),
N_("Garden of Delights"), N_("Overlays"), N_("Phantasmagorical turbulent wisps, like Hieronymus Bosch's Garden of Delights"),
N_("Diffuse light"), N_("ABCs"), N_("Basic diffuse bevel to use for building textures"),
N_("Cutout Glow"), N_("Shadows and Glows"), N_("In and out glow with a possible offset and colorizable flood"),
N_("HSL Bumps, matte"), N_("Bumps"), N_("Same as HSL bumps but with a diffuse reflection instead of a specular one"),
N_("Dark Emboss"), N_("Bumps"), N_("Emboss effect : 3D relief where white is replaced by black"),
N_("Simple blur"), N_("ABCs"), N_("Simple Gaussian blur, same as the blur slider in Fill and Stroke dialog"),
N_("Bubbly Bumps, matte"), N_("Bumps"), N_("Same as Bubbly Bumps but with a diffuse light instead of a specular one"),
N_("Emboss"), N_("Bumps"), N_("Emboss effect : Colors of the original images are preserved or modified by Blend"),
N_("Blotting paper"), N_("Textures"), N_("Inkblot on blotting paper"),
N_("Wax print"), N_("Textures"), N_("Wax print on tissue texture"),
N_("Inkblot"), N_("Textures"), N_("Inkblot on tissue or rough paper"),
N_("Torn edges"), N_("Distort"), N_("Displace the outside of shapes and pictures without altering their content"),
N_("Color outline, in"), N_("Morphology"), N_("A colorizable inner outline with adjustable width and blur"),
N_("Liquid"), N_("Textures"), N_("Colorizable filling with liquid transparency"),
N_("Watercolor"), N_("Textures"), N_("Cloudy watercolor effect"),
N_("Felt"), N_("Textures"), N_("Felt like texture with color turbulence and slightly darker at the edges"),
N_("Ink paint"), N_("Textures"), N_("Ink paint on paper with some turbulent color shift"),
N_("Tinted rainbow"), N_("Textures"), N_("Smooth rainbow colors melted along the edges and colorizable"),
N_("Melted rainbow"), N_("Textures"), N_("Smooth rainbow colors slightly melted along the edges"),
N_("Flex metal"), N_("Materials"), N_("Bright, polished uneven metal casting, colorizable"),
N_("Comics draft"), N_("Non realistic 3D shaders"), N_("Draft painted cartoon shading with a glassy look"),
N_("Comics fading"), N_("Non realistic 3D shaders"), N_("Cartoon paint style with some fading at the edges"),
N_("Smooth shader"), N_("Non realistic 3D shaders"), N_("Smooth shading with a graphite pencil grey"),
N_("Emboss shader"), N_("Non realistic 3D shaders"), N_("Combination of smooth shading and embossing"),
N_("Smooth shader dark"), N_("Non realistic 3D shaders"), N_("Dark version of non realistic smooth shading"),
N_("Comics"), N_("Non realistic 3D shaders"), N_("Imitation of black and white cartoon shading"),
N_("Satin"), N_("Non realistic 3D shaders"), N_("Silky close to mother of pearl shading"),
N_("Frosted glass"), N_("Non realistic 3D shaders"), N_("Non realistic frosted glass imitation"),
N_("Smooth shader contour"), N_("Non realistic 3D shaders"), N_("Contouring version of smooth shader"),
N_("Aluminium"), N_("Non realistic 3D shaders"), N_("Brushed aluminium shader"),
N_("Comics fluid"), N_("Non realistic 3D shaders"), N_("Fluid brushed cartoon drawing"),
N_("Chrome"), N_("Non realistic 3D shaders"), N_("Non realistic chrome shader with strong speculars"),
N_("Chrome dark"), N_("Non realistic 3D shaders"), N_("Dark version of chrome shading with a ground reflection simulation"),
N_("Wavy tartan"), N_("Overlays"), N_("Tartan pattern with a wavy displacement and bevel around the edges"),
N_("3D marble"), N_("Materials"), N_("3D warped marble texture"),
N_("3D wood"), N_("Materials"), N_("3D warped, fibered wood texture"),
N_("3D mother of pearl"), N_("Materials"), N_("3D warped, iridescent pearly shell texture"),
N_("Tiger fur"), N_("Overlays"), N_("Tiger fur pattern with folds and bevel around the edges"),
N_("Shaken liquid"), N_("Textures"), N_("Colorizable filling with flow inside like transparency"),
N_("Comics cream"), N_("Non realistic 3D shaders"), N_("Comics shader with creamy waves transparency"),
N_("Black Light"), N_("Color"), N_("Light areas turn to black"),
N_("Light eraser"), N_("Transparency utilities"), N_("Make the lightest parts of the object progressively transparent"),
N_("Noisy blur"), N_("Blurs"), N_("Small-scale roughening and blurring to edges and content"),
N_("Film grain"), N_("Image effects"), N_("Adds a small scale graininess"),
N_("HSL Bumps, transparent"), N_("Bumps"), N_("Highly flexible specular bump with transparency"),
N_("Drawing"), N_("Image effects"), N_("Give lead pencil or chromolithography or engraving or other effects to images and material filled objects"),
N_("Velvet Bumps"), N_("Bumps"), N_("Gives Smooth Bumps velvet like"),
N_("Alpha draw"), N_("Image effects, transparent"), N_("Gives a transparent drawing effect to bitmaps and materials"),
N_("Alpha draw, color"), N_("Image effects, transparent"), N_("Gives a transparent color fill effect to bitmaps and materials"),
N_("Chewing gum"), N_("Protrusions"), N_("Creates colorizable blotches which smoothly flow over the edges of the lines at their crossings"),
N_("Black outline"), N_("ABCs"), N_("Draws a black outline around"),
N_("Color outline"), N_("Morphology"), N_("Draws a colored outline around"),
N_("Inner Shadow"), N_("Shadows and Glows"), N_("Adds a colorizable drop shadow inside"),
N_("Dark and Glow"), N_("Shadows and Glows"), N_("Darkens the edge with an inner blur and adds a flexible glow"),
N_("Darken edges"), N_("Shadows and Glows"), N_("Darken the edges with an inner blur"),
N_("Warped rainbow"), N_("Textures"), N_("Smooth rainbow colors warped along the edges and colorizable"),
N_("Rough and dilate"), N_("Distort"), N_("Create a turbulent contour around"),
N_("Quadritone fantasy"), N_("Color"), N_("Replace hue by two colors"),
N_("Old postcard"), N_("Image effects"), N_("Slightly posterize and draw edges like on old printed postcards"),
N_("Fuzzy Glow"), N_("Shadows and Glows"), N_("Overlays a semi-transparent shifted copy to a blurred one"),
N_("Dots transparency"), N_("Image effects, transparent"), N_("Gives a pointillist HSL sensitive transparency"),
N_("Canvas transparency"), N_("Image effects, transparent"), N_("Gives a canvas like HSL sensitive transparency."),
N_("Smear transparency"), N_("Image effects, transparent"), N_("Paint objects with a transparent turbulence which turns around color edges"),
N_("Thick paint"), N_("Bumps"), N_("Thick painting effect with turbulence"),
N_("Burst"), N_("Textures"), N_("Burst balloon texture crumpled and with holes"),
N_("Embossed leather"), N_("Bumps"), N_("Combine a HSL edges detection bump with a leathery or woody and colorizable texture"),
N_("Carnaval"), N_("Overlays"), N_("White splotches evocating carnaval masks"),
N_("Plastify"), N_("Bumps"), N_("HSL edges detection bump with a wavy reflective surface effect and variable crumple"),
N_("Plaster"), N_("Bumps"), N_("Combine a HSL edges detection bump with a matte and crumpled surface effect"),
N_("Rough transparency"), N_("Image effects, transparent"), N_("Adds a turbulent transparency which displaces pixels at the same time"),
N_("Gouache"), N_("Textures"), N_("Partly opaque water color effect with bleed"),
N_("Alpha engraving"), N_("Image effects, transparent"), N_("Gives a transparent engraving effect with rough line and filling"),
N_("Alpha draw, liquid"), N_("Image effects, transparent"), N_("Gives a transparent fluid drawing effect with rough line and filling"),
N_("Liquid drawing"), N_("Image effects"), N_("Gives a fluid and wavy expressionist drawing effect to images"),
N_("Marbled ink"), N_("Image effects, transparent"), N_("Marbled transparency effect which conforms to image detected edges"),
N_("Thick acrylic"), N_("Bumps"), N_("Thick acrylic paint texture with high texture depth"),
N_("Alpha engraving B"), N_("Image effects, transparent"), N_("Gives a controllable roughness engraving effect to bitmaps and materials"),
N_("Lapping"), N_("Distort"), N_("Something like a water noise"),
N_("Monochrome transparency"), N_("Transparency utilities"), N_("Convert to a colorizable transparent positive or negative"),
N_("Duotone"), N_("Color"), N_("Change colors to a duotone palette"),
N_("Light eraser, negative"), N_("Transparency utilities"), N_("Like Light eraser but converts to negative"),
N_("Alpha repaint"), N_("Transparency utilities"), N_("Repaint anything monochrome"),
N_("Saturation map"), N_("Transparency utilities"), N_("Creates an approximative semi-transparent and colorizable image of the saturation levels"),
N_("Riddled"), N_("Textures"), N_("Riddle the surface and add bump to images"),
N_("Wrinkled varnish"), N_("Bumps"), N_("Thick glossy and translucent paint texture with high depth"),
N_("Canvas Bumps"), N_("Bumps"), N_("Canvas texture with an HSL sensitive height map"),
N_("Canvas Bumps, matte"), N_("Bumps"), N_("Same as Canvas Bumps but with a diffuse light instead of a specular one"),
N_("Canvas Bumps alpha"), N_("Image effects, transparent"), N_("Same as Canvas Bumps but with transparent highlights"),
N_("Lightness-Contrast"), N_("Color"), N_("Increase or decrease lightness and contrast"),
N_("Clean edges"), N_("ABCs"), N_("Removes or decreases glows and jaggeries around objects edges after applying some filters"),
N_("Bright metal"), N_("Bevels"), N_("Bright metallic effect for any color"),
N_("Deep colors plastic"), N_("Bevels"), N_("Transparent plastic with deep colors"),
N_("Melted jelly, matte"), N_("Bevels"), N_("Matte bevel with blurred edges"),
N_("Melted jelly"), N_("Bevels"), N_("Glossy bevel with blurred edges"),
N_("Combined lighting"), N_("Bevels"), N_("Basic specular bevel to use for building textures"),
N_("Tinfoil"), N_("Bumps"), N_("Metallic foil effect combining two lighting types and variable crumple"),
N_("Copper and chocolate"), N_("Bumps"), N_("Specular bump which can be easily converted from metallic to molded plastic effects"),
N_("Inner Glow"), N_("Shadows and Glows"), N_("Adds a colorizable glow inside"),
N_("Soft colors"), N_("Color"), N_("Adds a colorizable edges glow inside objects and pictures"),
N_("Relief print"), N_("Bumps"), N_("Bumps effect with a bevel, color flood and complex lighting"),
N_("Growing cells"), N_("Overlays"), N_("Random rounded living cells like fill"),
N_("Fluorescence"), N_("Color"), N_("Oversaturate colors which can be fluorescent in real world"),
N_("Tritone"), N_("Color"), N_("Create a tritone palette with hue selectable by flood"),
];
