char * stringlst = [
N_("Stripes 1:1"),
N_("Stripes 1:1 white"),
N_("Stripes 1:1.5"),
N_("Stripes 1:1.5 white"),
N_("Stripes 1:2"),
N_("Stripes 1:2 white"),
N_("Stripes 1:3"),
N_("Stripes 1:3 white"),
N_("Stripes 1:4"),
N_("Stripes 1:4 white"),
N_("Stripes 1:5"),
N_("Stripes 1:5 white"),
N_("Stripes 1:8"),
N_("Stripes 1:8 white"),
N_("Stripes 1:10"),
N_("Stripes 1:10 white"),
N_("Stripes 1:16"),
N_("Stripes 1:16 white"),
N_("Stripes 1:32"),
N_("Stripes 1:32 white"),
N_("Stripes 1:64"),
N_("Stripes 2:1"),
N_("Stripes 2:1 white"),
N_("Stripes 4:1"),
N_("Stripes 4:1 white"),
N_("Checkerboard"),
N_("Checkerboard white"),
N_("Packed circles"),
N_("Polka dots, small"),
N_("Polka dots, small white"),
N_("Polka dots, medium"),
N_("Polka dots, medium white"),
N_("Polka dots, large"),
N_("Polka dots, large white"),
N_("Wavy"),
N_("Wavy white"),
N_("Camouflage"),
N_("Ermine"),
N_("Sand (bitmap)"),
N_("Cloth (bitmap)"),
N_("Old paint (bitmap)"),
];
